stat svc
ilizian/java-explore-with-me pull request #3
Opened 2023-07-27 22:27 UTC by ilizian

2023-07-28 21:33 UTC, alexache requested changes

2023-07-28 21:33 UTC, alexache commented on ewm-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
А почему и здесь бы не использовать project.version?

2023-07-28 21:33 UTC, alexache commented on stats-service/stats-client/pom.xml
> +            <version>2.7.5</version>
Версии зависимостей должны быть заданы только в родительском модуле, через dependencyManagement

2023-07-28 21:33 UTC, alexache commented on stats-service/stats-client/src/main/java/ru/practicum/explore/ViewStatsClient.java
> +                "uris", uris,
Массив надо не передавать как есть, а переделывать в строку со значениями через запятую

2023-07-28 21:33 UTC, alexache commented on stats-service/stats-dto/src/main/java/ru/practicum/explore/EndpointHitDto.java
> +    private String app;
А валидации стоило бы тоже добавить

2023-07-28 21:33 UTC, alexache commented on stats-service/stats-server/src/main/java/ru/practicum/explore/StatsController.java
> +    EndpointHitDto addEndpointHit(@RequestBody EndpointHitDto endpointHitDto) throws ValidationException {
Модификатор доступа стоит добавить

2023-07-28 21:33 UTC, alexache commented on stats-service/stats-server/src/main/java/ru/practicum/explore/model/EndpointHit.java
> +                && app.equals(thisHit.app)
Для JPA моделей нежелательно использовать что либо кроме id в equals/hashcode

2023-07-28 21:33 UTC, alexache commented on stats-service/stats-server/src/main/java/ru/practicum/explore/repository/StatsRepository.java
> +    public List<ViewStats> findUniqueStats(
public излишен у методов внутри интерфейса, все методы и так публичны

2023-07-29 06:59 UTC, ilizian commented on ewm-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Исправлено

2023-07-29 07:04 UTC, ilizian commented on stats-service/stats-client/pom.xml
> +            <version>2.7.5</version>
Исправлено

2023-07-29 07:10 UTC, ilizian commented on stats-service/stats-client/src/main/java/ru/practicum/explore/ViewStatsClient.java
> +                "uris", uris,
Исправлено

2023-07-29 07:13 UTC, ilizian commented on stats-service/stats-dto/src/main/java/ru/practicum/explore/EndpointHitDto.java
> +    private String app;
Исправлено

2023-07-29 07:13 UTC, ilizian commented on stats-service/stats-server/src/main/java/ru/practicum/explore/StatsController.java
> +    EndpointHitDto addEndpointHit(@RequestBody EndpointHitDto endpointHitDto) throws ValidationException {
Исправлено

2023-07-29 07:14 UTC, ilizian commented on stats-service/stats-server/src/main/java/ru/practicum/explore/model/EndpointHit.java
> +                && app.equals(thisHit.app)
Исправлено

2023-07-29 07:15 UTC, ilizian commented on stats-service/stats-server/src/main/java/ru/practicum/explore/repository/StatsRepository.java
> +    public List<ViewStats> findUniqueStats(
Исправлено

2023-07-29 21:13 UTC, alexache approved these changes

2023-07-29 21:13 UTC, alexache commented on stats-service/stats-server/src/main/java/ru/practicum/explore/StatsController.java
> +    public EndpointHitDto addEndpointHit(@RequestBody EndpointHitDto endpointHitDto) throws ValidationException {
Не стоит ли @Valid добавить?

2023-07-30 14:49 UTC, ilizian commented on stats-service/stats-server/src/main/java/ru/practicum/explore/StatsController.java
> +    public EndpointHitDto addEndpointHit(@RequestBody EndpointHitDto endpointHitDto) throws ValidationException {
Да, забыл

2023-07-30 14:49 UTC, merged